// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJ0bVQkCtA0ebdwWD2xvJsGf9hQh9zqk',
    appId: '1:17268526518:android:608ca4284a188cc6eac517',
    messagingSenderId: '17268526518',
    projectId: 'hicoapp-73545',
    storageBucket: 'hicoapp-73545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2KK_37buwp0xdG0A0QhmzYqI46vgK70',
    appId: '1:17268526518:ios:e114620db089ea85eac517',
    messagingSenderId: '17268526518',
    projectId: 'hicoapp-73545',
    storageBucket: 'hicoapp-73545.appspot.com',
    iosClientId:
        '17268526518-6q28br1tnlhb69rgldgs5ae4pbhieq4t.apps.googleusercontent.com',
    iosBundleId: 'com.wap.hico',
  );
}
